-- GENERATED by scripts/introspect.py — do not edit by hand.
-- One ReplacingMergeTree table per entity, keyed by id, tombstone-aware.

-- entity: AutoTopup  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS auto_topup (
    `id` String,
    `coordinator` String DEFAULT '',
    `label` LowCardinality(String) DEFAULT '',
    `owner` String DEFAULT '',
    `recipient` String DEFAULT '',
    `recipient_token` String DEFAULT '',
    `threshold` Int256 DEFAULT 0,
    `transaction_hash` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Avatar  strategy: dual  mutable: True
CREATE TABLE IF NOT EXISTS avatar (
    `id` String,
    `accepted_invite_timestamp` Int64 DEFAULT 0,
    `avatar_type` LowCardinality(String) DEFAULT '',
    `block_number` UInt64 DEFAULT 0,
    `cid_v0` String DEFAULT '',
    `earned_from_invites` Int256 DEFAULT 0,
    `fee_collection_address` String DEFAULT '',
    `group_owner` String DEFAULT '',
    `invited_by` String DEFAULT '',
    `is_base_group` Bool DEFAULT false,
    `is_early_supporter` Bool DEFAULT false,
    `last_mint` Int64 DEFAULT 0,
    `log_index` Int64 DEFAULT 0,
    `migrated` Bool DEFAULT false,
    `mint_handler_address` String DEFAULT '',
    `primary_group` String DEFAULT '',
    `profile_id` String DEFAULT '',
    `timestamp` Int64 DEFAULT 0,
    `token_id` String DEFAULT '',
    `transaction_hash` String DEFAULT '',
    `transaction_index` Int64 DEFAULT 0,
    `treasury` String DEFAULT '',
    `trusts_given_count` Int64 DEFAULT 0,
    `trusts_given_count_v1` Int64 DEFAULT 0,
    `trusts_mutual_count` Int64 DEFAULT 0,
    `trusts_mutual_count_v1` Int64 DEFAULT 0,
    `trusts_received_count` Int64 DEFAULT 0,
    `trusts_received_count_v1` Int64 DEFAULT 0,
    `trusts_two_way_count` Int64 DEFAULT 0,
    `v1_stopped` Bool DEFAULT false,
    `v1_token_id` String DEFAULT '',
    `verification_badge` LowCardinality(String) DEFAULT '',
    `version` Int64 DEFAULT 0,
    `wrapped_token_demurrage_id` String DEFAULT '',
    `wrapped_token_id` String DEFAULT '',
    `wrapped_token_static_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: AvatarBalance  strategy: field_cursor  mutable: True
CREATE TABLE IF NOT EXISTS avatar_balance (
    `id` String,
    `avatar_id` String DEFAULT '',
    `balance` Int256 DEFAULT 0,
    `last_calculated` Int64 DEFAULT 0,
    `token_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: AvatarTotalBalanceV2  strategy: field_cursor  mutable: True
CREATE TABLE IF NOT EXISTS avatar_total_balance_v2 (
    `id` String,
    `balance` Int256 DEFAULT 0,
    `balance_pending` Int256 DEFAULT 0,
    `balance_static` Int256 DEFAULT 0,
    `balance_static_pending` Int256 DEFAULT 0,
    `last_burn` Int64 DEFAULT 0,
    `last_pending_update` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Cashback  strategy: field_cursor  mutable: True
CREATE TABLE IF NOT EXISTS cashback (
    `id` String,
    `gnosis_pay_address` String DEFAULT '',
    `last_status_update` Int64 DEFAULT 0,
    `last_status_update_transaction_hash` String DEFAULT '',
    `mint_transaction_hash` String DEFAULT '',
    `minted_at` Int64 DEFAULT 0,
    `minted_block` Int64 DEFAULT 0,
    `owner` String DEFAULT '',
    `status` Int64 DEFAULT 0,
    `token_id` Int256 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: CashbackStatusHistory  strategy: field_cursor  mutable: False
CREATE TABLE IF NOT EXISTS cashback_status_history (
    `id` String,
    `cashback_id` String DEFAULT '',
    `status` Int64 DEFAULT 0,
    `timestamp` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: CirclesBacking  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS circles_backing (
    `id` String,
    `backer_id` String DEFAULT '',
    `backing_asset` String DEFAULT '',
    `circles_backing_instance` String DEFAULT '',
    `completed_at` Int64 DEFAULT 0,
    `completed_block` Int64 DEFAULT 0,
    `completed_log_index` Int64 DEFAULT 0,
    `completed_tx` String DEFAULT '',
    `initiated_at` Int64 DEFAULT 0,
    `initiated_block` Int64 DEFAULT 0,
    `initiated_log_index` Int64 DEFAULT 0,
    `initiated_tx` String DEFAULT '',
    `lbp_address` String DEFAULT '',
    `personal_circles_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: CoordinatorState  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS coordinator_state (
    `id` String,
    `init_tx_hash` String DEFAULT '',
    `is_active` Bool DEFAULT false,
    `owner` String DEFAULT '',
    `recipient` String DEFAULT '',
    `recipient_token` String DEFAULT '',
    `threshold` Int256 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: EarnedFromInvite  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS earned_from_invite (
    `id` String,
    `amount` Int256 DEFAULT 0,
    `invitee_id` String DEFAULT '',
    `inviter_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: GnosisAppUser  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS gnosis_app_user (
    `id` String,
    `created_at_block` Int64 DEFAULT 0,
    `lifetime_cashback` Int256 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: GuardianModule  strategy: dual  mutable: True
CREATE TABLE IF NOT EXISTS guardian_module (
    `id` String,
    `block_number` UInt64 DEFAULT 0,
    `label` LowCardinality(String) DEFAULT '',
    `module_address` String DEFAULT '',
    `safe_address` String DEFAULT '',
    `timestamp` Int64 DEFAULT 0,
    `transaction_hash` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: HistoricalGNOBalance  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS historical_gno_balance (
    `id` String,
    `avatar_id` String DEFAULT '',
    `balance` Int256 DEFAULT 0,
    `current_balance` Int256 DEFAULT 0,
    `day_id` Int64 DEFAULT 0,
    `max_balance` Int256 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: InvestmentAccount  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS investment_account (
    `id` String,
    `coordinator` String DEFAULT '',
    `investment_token` String DEFAULT '',
    `is_active` Bool DEFAULT false,
    `owner` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Metri_Balance  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS metri_balance (
    `id` String,
    `balance` Int256 DEFAULT 0,
    `owner` String DEFAULT '',
    `token_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Metri_Order  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS metri_order (
    `id` String,
    `owner` String DEFAULT '',
    `token_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Metri_Pay_DelayModule  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS metri_pay_delay_module (
    `id` String,
    `deprecated` Bool DEFAULT false,
    `last_transaction_timestamp` Int64 DEFAULT 0,
    `safe_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Metri_Pay_DelayModuleOwner  strategy: field_cursor  mutable: False
CREATE TABLE IF NOT EXISTS metri_pay_delay_module_owner (
    `id` String,
    `delay_module_id` String DEFAULT '',
    `is_og` Bool DEFAULT false,
    `owner_address` String DEFAULT '',
    `timestamp` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Metri_Pay_RolesModule  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS metri_pay_roles_module (
    `id` String,
    `last_spendable` Int256 DEFAULT 0,
    `last_spent_at` Int64 DEFAULT 0,
    `safe_address` String DEFAULT '',
    `spending_limit` Int256 DEFAULT 0,
    `token_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Notification  strategy: field_cursor  mutable: False
CREATE TABLE IF NOT EXISTS notification (
    `id` String,
    `counterparty_id` String DEFAULT '',
    `notification_type` LowCardinality(String) DEFAULT '',
    `timestamp` Int64 DEFAULT 0,
    `to_address` String DEFAULT '',
    `to_avatar_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: PendingRecovery  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS pending_recovery (
    `id` String,
    `log_index` Int64 DEFAULT 0,
    `module_address` String DEFAULT '',
    `queue_nonce` Int256 DEFAULT 0,
    `safe_address` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Profile  strategy: field_cursor  mutable: True
CREATE TABLE IF NOT EXISTS profile (
    `id` String,
    `cid_v0` String DEFAULT '',
    `description` String DEFAULT '',
    `is_image_available` Bool DEFAULT false,
    `last_updated_block_number` Int64 DEFAULT 0,
    `location` String DEFAULT '',
    `name` String DEFAULT '',
    `symbol` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Swap  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS swap (
    `id` String,
    `app_data` String DEFAULT '',
    `buy_amount` Int256 DEFAULT 0,
    `buy_token` String DEFAULT '',
    `fee_amount` Int256 DEFAULT 0,
    `order_uid` String DEFAULT '',
    `owner` String DEFAULT '',
    `primary_group_id` String DEFAULT '',
    `receiver` String DEFAULT '',
    `sell_amount` Int256 DEFAULT 0,
    `sell_token` String DEFAULT '',
    `status` LowCardinality(String) DEFAULT '',
    `transaction_hash` String DEFAULT '',
    `valid_to` Int256 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Token  strategy: dual  mutable: True
CREATE TABLE IF NOT EXISTS token (
    `id` String,
    `block_number` UInt64 DEFAULT 0,
    `log_index` Int64 DEFAULT 0,
    `timestamp` Int64 DEFAULT 0,
    `token_owner_id` String DEFAULT '',
    `token_type` LowCardinality(String) DEFAULT '',
    `total_supply` Int256 DEFAULT 0,
    `transaction_hash` String DEFAULT '',
    `transaction_index` Int64 DEFAULT 0,
    `version` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: Transaction  strategy: block_cursor  mutable: False
CREATE TABLE IF NOT EXISTS transaction (
    `id` String,
    `block_number` UInt64 DEFAULT 0,
    `fee` Int256 DEFAULT 0,
    `fee_token` String DEFAULT '',
    `pending_until` Int64 DEFAULT 0,
    `timestamp` Int64 DEFAULT 0,
    `transaction_hash` String DEFAULT '',
    `transaction_index` Int64 DEFAULT 0,
    `user_op_hash` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id) PARTITION BY intDiv(block_number, 1000000);

-- entity: TransactionAction  strategy: field_cursor  mutable: False
CREATE TABLE IF NOT EXISTS transaction_action (
    `id` String,
    `auto_topup_id` String DEFAULT '',
    `avatar_id` String DEFAULT '',
    `guardian_module_id` String DEFAULT '',
    `swap_id` String DEFAULT '',
    `timestamp` Int64 DEFAULT 0,
    `transaction_id` String DEFAULT '',
    `transfer_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9)),
    INDEX idx_ta_txn transaction_id TYPE bloom_filter GRANULARITY 4,
    INDEX idx_ta_ts timestamp TYPE minmax GRANULARITY 4
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (avatar_id, timestamp, id) PARTITION BY toStartOfMonth(toDateTime(timestamp));

-- entity: Transfer  strategy: block_cursor  mutable: False
CREATE TABLE IF NOT EXISTS transfer (
    `id` String,
    `block_number` UInt64 DEFAULT 0,
    `extra_data` String DEFAULT '',
    `from` String DEFAULT '',
    `is_part_of_stream_or_hub` Bool DEFAULT false,
    `log_index` Int64 DEFAULT 0,
    `operator` String DEFAULT '',
    `participants` String DEFAULT '',
    `primary_group_id` String DEFAULT '',
    `to` String DEFAULT '',
    `token` String DEFAULT '',
    `transaction_hash` String DEFAULT '',
    `transfer_type` LowCardinality(String) DEFAULT '',
    `value` Int256 DEFAULT 0,
    `version` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id) PARTITION BY intDiv(block_number, 1000000);

-- entity: TrustRelation  strategy: dual  mutable: True
CREATE TABLE IF NOT EXISTS trust_relation (
    `id` String,
    `block_number` UInt64 DEFAULT 0,
    `expiry_time` UInt256 DEFAULT 0,
    `is_migrated` Bool DEFAULT false,
    `is_mutual` Bool DEFAULT false,
    `is_pending_until_register_human` Bool DEFAULT false,
    `limit` Int256 DEFAULT 0,
    `log_index` Int64 DEFAULT 0,
    `timestamp` Int64 DEFAULT 0,
    `transaction_index` Int64 DEFAULT 0,
    `trustee_id` String DEFAULT '',
    `truster_id` String DEFAULT '',
    `version` Int64 DEFAULT 0,
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);

-- entity: V1TokenPendingStop  strategy: full_rescan  mutable: True
CREATE TABLE IF NOT EXISTS v1_token_pending_stop (
    `id` String,
    `avatar_id` String DEFAULT '',
    `_deleted` UInt8 DEFAULT 0,
    `_seen_version` UInt64 DEFAULT 0,
    `ingested_at` DateTime DEFAULT now(),
    `_synced_block` UInt64 DEFAULT 0,
    `insert_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
) ENGINE = ReplacingMergeTree(insert_version) ORDER BY (id);
