"""Entity registry dataclasses + sync-strategy enum.

An EntitySpec fully describes how one GraphQL entity maps to a ClickHouse typed
table and how it is kept in sync. The registry is generated by
scripts/introspect.py (-> generated.py) and overlaid with config/entities.yaml
(-> overrides.py).
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class SyncStrategy(str, Enum):
    BLOCK_CURSOR = "block_cursor"   # immutable, append-only, block-stamped
    FIELD_CURSOR = "field_cursor"   # mutable with a monotonic update field
    FULL_RESCAN = "full_rescan"     # mutable/static, no usable cursor
    DUAL = "dual"                   # block_cursor discovery + periodic full rescan


@dataclass
class FieldSpec:
    gql_name: str            # GraphQL field name (camelCase)
    ch_name: str             # ClickHouse column name (snake_case)
    ch_type: str             # ClickHouse type, e.g. "String", "UInt256", "LowCardinality(String)"
    nullable: bool = True    # upstream nullability (we still use sentinels, not Nullable())


@dataclass
class EntitySpec:
    name: str                              # ClickHouse table name (lower_snake)
    gql_type: str                          # GraphQL type name
    root_field: str                        # GraphQL root query field name
    fields: List[FieldSpec] = field(default_factory=list)

    strategy: SyncStrategy = SyncStrategy.FULL_RESCAN
    cursor_field: Optional[str] = None     # GraphQL field used as incremental cursor
    block_field: Optional[str] = None      # GraphQL block-number field, if any
    ts_field: Optional[str] = None         # immutable creation timestamp field, if any
    version_field: Optional[str] = None    # upstream monotonic version field, if any

    mutable: bool = True
    deletable: bool = True

    partition_expr: str = ""               # ClickHouse PARTITION BY expression (or "")
    page_size: int = 1000
    rescan_interval_s: int = 300
    enabled: bool = True

    # ── helpers ───────────────────────────────────────────────────────────────
    @property
    def ch_field_names(self) -> List[str]:
        return [f.ch_name for f in self.fields]

    def field_by_gql(self, gql_name: str) -> Optional[FieldSpec]:
        for f in self.fields:
            if f.gql_name == gql_name:
                return f
        return None

    def ch_name_for(self, gql_name: str) -> Optional[str]:
        f = self.field_by_gql(gql_name)
        return f.ch_name if f else None

    @property
    def cursor_ch_name(self) -> Optional[str]:
        return self.ch_name_for(self.cursor_field) if self.cursor_field else None

    @property
    def block_ch_name(self) -> Optional[str]:
        return self.ch_name_for(self.block_field) if self.block_field else None

    @property
    def version_column(self) -> str:
        """ReplacingMergeTree version column for the typed table."""
        if self.version_field:
            ch = self.ch_name_for(self.version_field)
            if ch:
                return ch
        return "insert_version"

    @property
    def gql_field_names(self) -> List[str]:
        return [f.gql_name for f in self.fields]
